// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC09WAz8hF-0csATgoeiOlcR97SNETJ6IU',
    appId: '1:988514202552:web:8dd961a8ec3b537b06554d',
    messagingSenderId: '988514202552',
    projectId: 'inclasswork12',
    authDomain: 'inclasswork12.firebaseapp.com',
    storageBucket: 'inclasswork12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBXB0qviEK5LZ3nt0BncVU4xw-5N0AJNQ',
    appId: '1:988514202552:android:3013afabbc5a740706554d',
    messagingSenderId: '988514202552',
    projectId: 'inclasswork12',
    storageBucket: 'inclasswork12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBggRrKZWE6tq9NcUzddY8uBO5hUet8bYA',
    appId: '1:988514202552:ios:af229a16e80bda5706554d',
    messagingSenderId: '988514202552',
    projectId: 'inclasswork12',
    storageBucket: 'inclasswork12.firebasestorage.app',
    iosBundleId: 'com.example.inClassActivity12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBggRrKZWE6tq9NcUzddY8uBO5hUet8bYA',
    appId: '1:988514202552:ios:af229a16e80bda5706554d',
    messagingSenderId: '988514202552',
    projectId: 'inclasswork12',
    storageBucket: 'inclasswork12.firebasestorage.app',
    iosBundleId: 'com.example.inClassActivity12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC09WAz8hF-0csATgoeiOlcR97SNETJ6IU',
    appId: '1:988514202552:web:dbe7ab874463eeb606554d',
    messagingSenderId: '988514202552',
    projectId: 'inclasswork12',
    authDomain: 'inclasswork12.firebaseapp.com',
    storageBucket: 'inclasswork12.firebasestorage.app',
  );
}
